# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: workflow_dispatch


jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt
    - name: Run ETL Process
      env: # Or as an environment variable
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.DEV_GOOGLE_JSON_KEY }}
        bq_project_id: ${{ secrets.bq_project_id }}
        bq_dataset_id: ${{ secrets.bq_dataset_id }}
        bq_table_id: ${{ secrets.bq_table_id }}

      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS_JSON > keys.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/keys.json
        python main.py

